# Generated by Django 5.0.3 on 2024-04-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DZ2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orders',
            table='Order',
        ),
    ]
