# Generated by Django 5.0.3 on 2024-04-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DZ2', '0002_alter_orders_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('id',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='userss',
            name='date_create',
            field=models.DateField(),
        ),
    ]
